# Generated by Django 5.0.6 on 2024-05-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0002_sensor_status_operacional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='obs',
            new_name='observacao',
        ),
    ]
