# Generated by Django 5.0.6 on 2024-05-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0003_rename_obs_sensor_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='unidade_medida',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
